import type { Product } from "@/types";

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: "1",
    slug: "lg-inverter-ac-18000",
    title: "کولر گازی اینورتر ۱۸۰۰۰ ال‌جی",
    brand: "LG",
    price: 55000000,
    oldPrice: 65000000,
    image: "https://placehold.co/400x400/eaf2f7/0b3b5c?text=LG+AC",
    rating: 4.8,
    reviewCount: 124,
    category: "cooler",
    tags: ["sale", "popular"],
    inStock: true,
  },
  {
    id: "2",
    slug: "samsung-robot-vacuum",
    title: "جارو رباتیک هوشمند سامسونگ",
    brand: "Samsung",
    price: 18750000,
    image: "https://placehold.co/400x400/eaf2f7/0b3b5c?text=Samsung+Robot",
    rating: 4.2,
    reviewCount: 89,
    category: "vacuum",
    tags: ["new", "popular"],
    inStock: true,
  },
  {
    id: "3",
    slug: "xiaomi-washing-machine-12kg",
    title: "ماشین لباسشویی ۱۲ کیلویی شیائومی",
    brand: "Xiaomi",
    price: 38200000,
    image: "https://placehold.co/400x400/eaf2f7/0b3b5c?text=Xiaomi+Washer",
    rating: 5.0,
    reviewCount: 210,
    category: "washer",
    tags: ["popular"],
    inStock: true,
  },
  {
    id: "4",
    slug: "lg-side-by-side-fridge",
    title: "یخچال ساید بای ساید ال‌جی",
    brand: "LG",
    price: 42500000,
    oldPrice: 53000000,
    image: "https://placehold.co/400x400/eaf2f7/0b3b5c?text=LG+Fridge",
    rating: 4.5,
    reviewCount: 156,
    category: "fridge",
    tags: ["sale"],
    inStock: true,
  },
  {
    id: "5",
    slug: "bosch-gas-stove-5-burner",
    title: "اجاق گاز ۵ شعله بوش",
    brand: "Bosch",
    price: 29900000,
    image: "https://placehold.co/400x400/eaf2f7/0b3b5c?text=Bosch+Stove",
    rating: 4.8,
    reviewCount: 67,
    category: "cooker",
    tags: ["new"],
    inStock: true,
  },
  {
    id: "6",
    slug: "hisense-microwave-smart",
    title: "مایکروویو هوشمند هایسنس",
    brand: "Hisense",
    price: 22300000,
    oldPrice: 24800000,
    image: "https://placehold.co/400x400/eaf2f7/0b3b5c?text=Hisense+MW",
    rating: 4.9,
    reviewCount: 45,
    category: "cooker",
    tags: ["popular", "sale"],
    inStock: true,
  },
  {
    id: "7",
    slug: "snowa-dishwasher",
    title: "ماشین ظرفشویی اسنوا ۱۴ نفره",
    brand: "Snowa",
    price: 34500000,
    image: "https://placehold.co/400x400/eaf2f7/0b3b5c?text=Snowa+DW",
    rating: 4.4,
    reviewCount: 78,
    category: "washer",
    tags: ["popular"],
    inStock: true,
  },
  {
    id: "8",
    slug: "pakshoma-water-cooler",
    title: "کولر آبی پاکشوما ۷۰۰۰",
    brand: "Pakshoma",
    price: 12800000,
    oldPrice: 14500000,
    image: "https://placehold.co/400x400/eaf2f7/0b3b5c?text=Pakshoma+Cooler",
    rating: 4.1,
    reviewCount: 32,
    category: "cooler",
    tags: ["sale"],
    inStock: true,
  },
  {
    id: "9",
    slug: "beko-built-in-oven",
    title: "فر توکار بکو ۶۰ سانتی",
    brand: "Beko",
    price: 27600000,
    image: "https://placehold.co/400x400/eaf2f7/0b3b5c?text=Beko+Oven",
    rating: 4.6,
    reviewCount: 91,
    category: "cooker",
    tags: ["new"],
    inStock: true,
  },
  {
    id: "10",
    slug: "daewoo-microwave",
    title: "مایکروویو دوو ۲۵ لیتری",
    brand: "Daewoo",
    price: 15900000,
    image: "https://placehold.co/400x400/eaf2f7/0b3b5c?text=Daewoo+MW",
    rating: 4.0,
    reviewCount: 28,
    category: "cooker",
    tags: [],
    inStock: false,
  },
  {
    id: "11",
    slug: "midea-air-fryer",
    title: "سرخ‌کن بدون روغن میدیا ۵ لیتری",
    brand: "Midea",
    price: 8900000,
    oldPrice: 11200000,
    image: "https://placehold.co/400x400/eaf2f7/0b3b5c?text=Midea+Fryer",
    rating: 4.7,
    reviewCount: 189,
    category: "cooker",
    tags: ["sale", "popular"],
    inStock: true,
  },
  {
    id: "12",
    slug: "whirlpool-dryer",
    title: "خشک‌کن وستل ۸ کیلویی",
    brand: "Whirlpool",
    price: 41200000,
    image: "https://placehold.co/400x400/eaf2f7/0b3b5c?text=Whirlpool+Dryer",
    rating: 4.3,
    reviewCount: 56,
    category: "washer",
    tags: ["new"],
    inStock: true,
  },
];

export const FILTER_BRANDS = [
  "LG",
  "Samsung",
  "Xiaomi",
  "Bosch",
  "Hisense",
  "Snowa",
  "Pakshoma",
  "Beko",
  "Daewoo",
  "Midea",
  "Whirlpool",
];

export const SORT_OPTIONS = [
  { value: "newest", label: "جدیدترین" },
  { value: "cheapest", label: "ارزان‌ترین" },
  { value: "expensive", label: "گران‌ترین" },
  { value: "popular", label: "پرفروش‌ترین" },
  { value: "rating", label: "محبوب‌ترین" },
];